### ISSUE TITLE
SetConstr is not defined when using json 

### ISSUE THREAD

**Issue by freevryheid** [pragmagic/karax#11] opened 2017-05-16 03:18 UTC
I assume the json mod is nim js friendly.

Reproduce using the following as source after compiling to js in the default html template:
```nim
include karaxprelude
import json
var jString = "{}"
var jNode = parseJson(jString)
```

**Comment by bluenote10** [comment] 2017-05-16 06:20
This works for me without problems, the generated js output contains:

```
function setConstr() {

      var result = {};
      for (var i = 0; i < arguments.length; ++i) {
        var x = arguments[i];
        if (typeof(x) == "object") {
          for (var j = x[0]; j <= x[1]; ++j) {
            result[j] = true;
          }
        } else {
          result[x] = true;
        }
      }
      return result;
    }
```

Do you really see usage of upper-case `SetConstr`?

**Comment by Araq** [comment] 2017-05-16 13:10
This was a regression in devel and has been fixed in devel.

**Closed by Araq** 2017-05-16 13:10 UTC
